// GENERATED by scripts/assets-fetch.mjs — do not edit. Run `npm run assets`.
/* eslint-disable */
export interface ModelInfo { id: string; url: string; kb: number; tris: number; size: [number, number, number]; min: number[]; max: number[]; anims: string[]; nodes: string[] }
export const MODELS = {
 "plane-cesium-air": {
  "id": "plane-cesium-air",
  "url": "/models/plane-cesium-air.glb",
  "kb": 319,
  "tris": 5840,
  "size": [
   25.737,
   7.76,
   21.402
  ],
  "min": [
   -12.868,
   -2.296,
   -13.397
  ],
  "max": [
   12.868,
   5.464,
   8.005
  ],
  "anims": [
   "Prop__2_Action_Prop",
   "PropAction_Prop__2_"
  ],
  "nodes": [
   "Prop",
   "Prop__2_",
   "Cesium_Air"
  ]
 },
 "plane-aerobatic": {
  "id": "plane-aerobatic",
  "url": "/models/plane-aerobatic.glb",
  "kb": 1354,
  "tris": 29563,
  "size": [
   0.292,
   0.104,
   0.22
  ],
  "min": [
   -0.146,
   0,
   -0.097
  ],
  "max": [
   0.146,
   0.104,
   0.123
  ],
  "anims": [
   "idle",
   "flight_path_1",
   "flight_path_2",
   "flight_path_3"
  ],
  "nodes": [
   "body_joint.5",
   "Rear_Wheel.8",
   "skeletal.3",
   "aerobatic_plane.2",
   "root.4",
   "L_Front_Wheel.6",
   "R_Front_Wheel.7",
   "Propellor_Joint.9"
  ]
 },
 "balloon": {
  "id": "balloon",
  "url": "/models/balloon.glb",
  "kb": 393,
  "tris": 13224,
  "size": [
   14.47,
   18.542,
   14.47
  ],
  "min": [
   -7.023,
   -1.7,
   -7.447
  ],
  "max": [
   7.447,
   16.842,
   7.023
  ],
  "anims": [],
  "nodes": []
 },
 "drone": {
  "id": "drone",
  "url": "/models/drone.glb",
  "kb": 210,
  "tris": 3412,
  "size": [
   5.275,
   1.105,
   5.041
  ],
  "min": [
   -2.637,
   -0.156,
   -2.393
  ],
  "max": [
   2.637,
   0.949,
   2.648
  ],
  "anims": [
   "Fly"
  ],
  "nodes": [
   "Antenna_low",
   "Base_low",
   "Body_low",
   "Lens_low",
   "MotorBackLeft_low",
   "MotorBackRight_low",
   "MotorFrontLeft_low",
   "MotorFrontRight_low",
   "PropClockwiseBack_low",
   "PropClockwiseFront_low",
   "PropCounterClockwiseBack_low",
   "PropCounterClockwiseFront_low"
  ]
 },
 "bird-flamingo": {
  "id": "bird-flamingo",
  "url": "/models/bird-flamingo.glb",
  "kb": 73,
  "tris": 542,
  "size": [
   52.2,
   89.1,
   176.6
  ],
  "min": [
   -25.5,
   -78.4,
   -76.2
  ],
  "max": [
   26.7,
   10.7,
   100.4
  ],
  "anims": [
   "flamingo_flyA_"
  ],
  "nodes": []
 },
 "bird-parrot": {
  "id": "bird-parrot",
  "url": "/models/bird-parrot.glb",
  "kb": 91,
  "tris": 626,
  "size": [
   79.5,
   33.7,
   100.5
  ],
  "min": [
   -39,
   -13.9,
   -76.1
  ],
  "max": [
   40.5,
   19.8,
   24.4
  ],
  "anims": [
   "parrot_A_"
  ],
  "nodes": []
 },
 "bird-stork": {
  "id": "bird-stork",
  "url": "/models/bird-stork.glb",
  "kb": 72,
  "tris": 542,
  "size": [
   196.8,
   29.9,
   174.3
  ],
  "min": [
   -98.4,
   -6,
   -82.3
  ],
  "max": [
   98.4,
   23.9,
   92
  ],
  "anims": [
   "storkFly_B_"
  ],
  "nodes": []
 },
 "coin": {
  "id": "coin",
  "url": "/models/coin.glb",
  "kb": 14,
  "tris": 252,
  "size": [
   0.415,
   0.417,
   0.167
  ],
  "min": [
   -0.208,
   0,
   -0.083
  ],
  "max": [
   0.208,
   0.417,
   0.083
  ],
  "anims": [],
  "nodes": [
   "coin"
  ]
 },
 "cloud": {
  "id": "cloud",
  "url": "/models/cloud.glb",
  "kb": 17,
  "tris": 204,
  "size": [
   1,
   1,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   1,
   0.5
  ],
  "anims": [],
  "nodes": [
   "cloud"
  ]
 },
 "flag": {
  "id": "flag",
  "url": "/models/flag.glb",
  "kb": 11,
  "tris": 132,
  "size": [
   0.2,
   1.235,
   0.685
  ],
  "min": [
   -0.1,
   0,
   -0.1
  ],
  "max": [
   0.1,
   1.235,
   0.585
  ],
  "anims": [],
  "nodes": [
   "flag"
  ]
 },
 "kn-building-a": {
  "id": "kn-building-a",
  "url": "/models/kn-building-a.glb",
  "kb": 28,
  "tris": 452,
  "size": [
   1,
   0.95,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   0.95,
   0.5
  ],
  "anims": [],
  "nodes": [
   "building-small-a"
  ]
 },
 "kn-building-b": {
  "id": "kn-building-b",
  "url": "/models/kn-building-b.glb",
  "kb": 34,
  "tris": 600,
  "size": [
   1,
   1.626,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   1.626,
   0.5
  ],
  "anims": [],
  "nodes": [
   "building-small-b"
  ]
 },
 "kn-building-c": {
  "id": "kn-building-c",
  "url": "/models/kn-building-c.glb",
  "kb": 49,
  "tris": 834,
  "size": [
   1,
   1.75,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   1.75,
   0.5
  ],
  "anims": [],
  "nodes": [
   "building-small-c"
  ]
 },
 "kn-building-d": {
  "id": "kn-building-d",
  "url": "/models/kn-building-d.glb",
  "kb": 27,
  "tris": 448,
  "size": [
   1,
   1,
   1.05
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   1,
   0.55
  ],
  "anims": [],
  "nodes": [
   "building-small-d"
  ]
 },
 "kn-garage": {
  "id": "kn-garage",
  "url": "/models/kn-garage.glb",
  "kb": 15,
  "tris": 196,
  "size": [
   1,
   0.55,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   0.55,
   0.5
  ],
  "anims": [],
  "nodes": [
   "building-garage"
  ]
 },
 "kn-trees": {
  "id": "kn-trees",
  "url": "/models/kn-trees.glb",
  "kb": 25,
  "tris": 380,
  "size": [
   1,
   0.636,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   0.636,
   0.5
  ],
  "anims": [],
  "nodes": [
   "grass-trees"
  ]
 },
 "kn-trees-tall": {
  "id": "kn-trees-tall",
  "url": "/models/kn-trees-tall.glb",
  "kb": 31,
  "tris": 472,
  "size": [
   1.072,
   0.76,
   1.006
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.572,
   0.76,
   0.506
  ],
  "anims": [],
  "nodes": [
   "grass-trees-tall"
  ]
 },
 "kn-fountain": {
  "id": "kn-fountain",
  "url": "/models/kn-fountain.glb",
  "kb": 11,
  "tris": 152,
  "size": [
   1,
   0.536,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   0.536,
   0.5
  ],
  "anims": [],
  "nodes": [
   "pavement-fountain"
  ]
 },
 "windmill": {
  "id": "windmill",
  "url": "/models/windmill.glb",
  "kb": 149,
  "tris": 2653,
  "size": [
   1.126,
   1.458,
   0.817
  ],
  "min": [
   -0.558,
   0,
   -0.379
  ],
  "max": [
   0.568,
   1.458,
   0.438
  ],
  "anims": [],
  "nodes": [
   "building_windmill_top_fan_red",
   "building_windmill_top_red",
   "building_windmill_red"
  ]
 },
 "watermill": {
  "id": "watermill",
  "url": "/models/watermill.glb",
  "kb": 119,
  "tris": 1921,
  "size": [
   1.05,
   1.568,
   1.236
  ],
  "min": [
   -0.525,
   -0.35,
   -0.37
  ],
  "max": [
   0.525,
   1.218,
   0.866
  ],
  "anims": [],
  "nodes": [
   "building_watermill_wheel_red",
   "building_watermill_red"
  ]
 },
 "home-a": {
  "id": "home-a",
  "url": "/models/home-a.glb",
  "kb": 64,
  "tris": 1011,
  "size": [
   0.792,
   0.93,
   0.854
  ],
  "min": [
   -0.396,
   0,
   -0.469
  ],
  "max": [
   0.396,
   0.93,
   0.385
  ],
  "anims": [],
  "nodes": [
   "building_home_A_red"
  ]
 },
 "home-b": {
  "id": "home-b",
  "url": "/models/home-b.glb",
  "kb": 90,
  "tris": 1393,
  "size": [
   0.875,
   1.28,
   1.099
  ],
  "min": [
   -0.439,
   0,
   -0.539
  ],
  "max": [
   0.436,
   1.28,
   0.56
  ],
  "anims": [],
  "nodes": [
   "building_home_B_red"
  ]
 },
 "church": {
  "id": "church",
  "url": "/models/church.glb",
  "kb": 97,
  "tris": 1601,
  "size": [
   1.029,
   1.645,
   1.155
  ],
  "min": [
   -0.514,
   0,
   -0.56
  ],
  "max": [
   0.514,
   1.645,
   0.595
  ],
  "anims": [],
  "nodes": [
   "building_church_red"
  ]
 },
 "castle": {
  "id": "castle",
  "url": "/models/castle.glb",
  "kb": 320,
  "tris": 5659,
  "size": [
   1.975,
   3.979,
   2.256
  ],
  "min": [
   -0.988,
   0,
   -1.128
  ],
  "max": [
   0.988,
   3.979,
   1.128
  ],
  "anims": [],
  "nodes": [
   "building_castle_red"
  ]
 },
 "tower-a": {
  "id": "tower-a",
  "url": "/models/tower-a.glb",
  "kb": 120,
  "tris": 2138,
  "size": [
   0.993,
   2.192,
   1.153
  ],
  "min": [
   -0.497,
   0,
   -0.573
  ],
  "max": [
   0.497,
   2.192,
   0.58
  ],
  "anims": [],
  "nodes": [
   "building_tower_A_top_red",
   "building_tower_A_red"
  ]
 },
 "well": {
  "id": "well",
  "url": "/models/well.glb",
  "kb": 51,
  "tris": 726,
  "size": [
   0.652,
   0.826,
   0.751
  ],
  "min": [
   -0.315,
   0,
   -0.375
  ],
  "max": [
   0.337,
   0.826,
   0.375
  ],
  "anims": [],
  "nodes": [
   "building_well_red"
  ]
 },
 "tavern": {
  "id": "tavern",
  "url": "/models/tavern.glb",
  "kb": 176,
  "tris": 2992,
  "size": [
   1.172,
   1.397,
   1.332
  ],
  "min": [
   -0.595,
   0,
   -0.702
  ],
  "max": [
   0.577,
   1.397,
   0.63
  ],
  "anims": [],
  "nodes": [
   "building_tavern_red"
  ]
 },
 "lumbermill": {
  "id": "lumbermill",
  "url": "/models/lumbermill.glb",
  "kb": 174,
  "tris": 3170,
  "size": [
   1.367,
   1.708,
   1.189
  ],
  "min": [
   -0.686,
   -0.004,
   -0.459
  ],
  "max": [
   0.681,
   1.704,
   0.73
  ],
  "anims": [],
  "nodes": [
   "building_lumbermill_saw_red",
   "building_lumbermill_top_red",
   "building_lumbermill_red"
  ]
 },
 "mine": {
  "id": "mine",
  "url": "/models/mine.glb",
  "kb": 74,
  "tris": 1126,
  "size": [
   1.606,
   1.137,
   1.92
  ],
  "min": [
   -0.817,
   0,
   -1.02
  ],
  "max": [
   0.789,
   1.137,
   0.9
  ],
  "anims": [],
  "nodes": [
   "building_mine_red"
  ]
 },
 "grain": {
  "id": "grain",
  "url": "/models/grain.glb",
  "kb": 23,
  "tris": 230,
  "size": [
   1.874,
   0.394,
   2.094
  ],
  "min": [
   -0.937,
   0,
   -1.047
  ],
  "max": [
   0.937,
   0.394,
   1.047
  ],
  "anims": [],
  "nodes": [
   "building_grain"
  ]
 },
 "tree-a": {
  "id": "tree-a",
  "url": "/models/tree-a.glb",
  "kb": 13,
  "tris": 50,
  "size": [
   0.574,
   1.196,
   0.547
  ],
  "min": [
   -0.288,
   -0.103,
   -0.302
  ],
  "max": [
   0.286,
   1.094,
   0.245
  ],
  "anims": [],
  "nodes": [
   "tree_single_A"
  ]
 },
 "tree-b": {
  "id": "tree-b",
  "url": "/models/tree-b.glb",
  "kb": 17,
  "tris": 220,
  "size": [
   0.685,
   1.213,
   0.72
  ],
  "min": [
   -0.342,
   -0.1,
   -0.36
  ],
  "max": [
   0.342,
   1.113,
   0.36
  ],
  "anims": [],
  "nodes": [
   "tree_single_B"
  ]
 },
 "trees-a-l": {
  "id": "trees-a-l",
  "url": "/models/trees-a-l.glb",
  "kb": 65,
  "tris": 864,
  "size": [
   1.945,
   0.926,
   1.967
  ],
  "min": [
   -0.968,
   -0.013,
   -0.991
  ],
  "max": [
   0.977,
   0.913,
   0.975
  ],
  "anims": [],
  "nodes": [
   "trees_A_large"
  ]
 },
 "trees-a-m": {
  "id": "trees-a-m",
  "url": "/models/trees-a-m.glb",
  "kb": 41,
  "tris": 480,
  "size": [
   1.751,
   1.295,
   1.814
  ],
  "min": [
   -0.861,
   -0.02,
   -0.873
  ],
  "max": [
   0.89,
   1.275,
   0.941
  ],
  "anims": [],
  "nodes": [
   "trees_A_medium"
  ]
 },
 "trees-b-l": {
  "id": "trees-b-l",
  "url": "/models/trees-b-l.glb",
  "kb": 60,
  "tris": 1540,
  "size": [
   1.849,
   1.175,
   1.932
  ],
  "min": [
   -0.907,
   -0.022,
   -0.986
  ],
  "max": [
   0.942,
   1.153,
   0.947
  ],
  "anims": [],
  "nodes": [
   "trees_B_large"
  ]
 },
 "trees-b-m": {
  "id": "trees-b-m",
  "url": "/models/trees-b-m.glb",
  "kb": 46,
  "tris": 1100,
  "size": [
   1.864,
   1.174,
   1.833
  ],
  "min": [
   -0.892,
   -0.021,
   -0.974
  ],
  "max": [
   0.972,
   1.153,
   0.86
  ],
  "anims": [],
  "nodes": [
   "trees_B_medium"
  ]
 },
 "rock-a": {
  "id": "rock-a",
  "url": "/models/rock-a.glb",
  "kb": 11,
  "tris": 18,
  "size": [
   0.298,
   0.069,
   0.284
  ],
  "min": [
   -0.149,
   0,
   -0.157
  ],
  "max": [
   0.149,
   0.069,
   0.127
  ],
  "anims": [],
  "nodes": [
   "rock_single_A"
  ]
 },
 "rock-b": {
  "id": "rock-b",
  "url": "/models/rock-b.glb",
  "kb": 11,
  "tris": 26,
  "size": [
   0.287,
   0.135,
   0.25
  ],
  "min": [
   -0.142,
   0,
   -0.128
  ],
  "max": [
   0.145,
   0.135,
   0.122
  ],
  "anims": [],
  "nodes": [
   "rock_single_B"
  ]
 },
 "rock-c": {
  "id": "rock-c",
  "url": "/models/rock-c.glb",
  "kb": 12,
  "tris": 40,
  "size": [
   0.344,
   0.195,
   0.344
  ],
  "min": [
   -0.185,
   0,
   -0.182
  ],
  "max": [
   0.159,
   0.195,
   0.162
  ],
  "anims": [],
  "nodes": [
   "rock_single_C"
  ]
 },
 "rock-d": {
  "id": "rock-d",
  "url": "/models/rock-d.glb",
  "kb": 11,
  "tris": 22,
  "size": [
   0.287,
   0.163,
   0.25
  ],
  "min": [
   -0.142,
   0,
   -0.13
  ],
  "max": [
   0.145,
   0.163,
   0.12
  ],
  "anims": [],
  "nodes": [
   "rock_single_D"
  ]
 },
 "rock-e": {
  "id": "rock-e",
  "url": "/models/rock-e.glb",
  "kb": 14,
  "tris": 71,
  "size": [
   0.488,
   0.195,
   0.348
  ],
  "min": [
   -0.255,
   0,
   -0.185
  ],
  "max": [
   0.233,
   0.195,
   0.163
  ],
  "anims": [],
  "nodes": [
   "rock_single_E"
  ]
 },
 "mountain-a": {
  "id": "mountain-a",
  "url": "/models/mountain-a.glb",
  "kb": 17,
  "tris": 120,
  "size": [
   1.801,
   1.425,
   1.876
  ],
  "min": [
   -0.894,
   0,
   -0.937
  ],
  "max": [
   0.907,
   1.425,
   0.939
  ],
  "anims": [],
  "nodes": [
   "mountain_A"
  ]
 },
 "mountain-b": {
  "id": "mountain-b",
  "url": "/models/mountain-b.glb",
  "kb": 17,
  "tris": 120,
  "size": [
   1.801,
   1.77,
   1.876
  ],
  "min": [
   -0.888,
   0,
   -0.934
  ],
  "max": [
   0.913,
   1.77,
   0.942
  ],
  "anims": [],
  "nodes": [
   "mountain_B"
  ]
 },
 "mountain-c": {
  "id": "mountain-c",
  "url": "/models/mountain-c.glb",
  "kb": 22,
  "tris": 200,
  "size": [
   1.759,
   1.508,
   2.023
  ],
  "min": [
   -0.851,
   0,
   -1.018
  ],
  "max": [
   0.907,
   1.508,
   1.005
  ],
  "anims": [],
  "nodes": [
   "mountain_C"
  ]
 },
 "mountain-a-trees": {
  "id": "mountain-a-trees",
  "url": "/models/mountain-a-trees.glb",
  "kb": 36,
  "tris": 468,
  "size": [
   1.855,
   2.176,
   1.876
  ],
  "min": [
   -0.894,
   0,
   -0.937
  ],
  "max": [
   0.962,
   2.176,
   0.939
  ],
  "anims": [],
  "nodes": [
   "mountain_A_grass_trees"
  ]
 },
 "hills-a-trees": {
  "id": "hills-a-trees",
  "url": "/models/hills-a-trees.glb",
  "kb": 40,
  "tris": 518,
  "size": [
   1.755,
   1.332,
   1.737
  ],
  "min": [
   -0.821,
   0,
   -0.833
  ],
  "max": [
   0.934,
   1.332,
   0.904
  ],
  "anims": [],
  "nodes": [
   "hills_A_trees"
  ]
 },
 "cloud-big": {
  "id": "cloud-big",
  "url": "/models/cloud-big.glb",
  "kb": 24,
  "tris": 672,
  "size": [
   3.607,
   1.946,
   2.242
  ],
  "min": [
   -1.797,
   -0.884,
   -1.094
  ],
  "max": [
   1.81,
   1.062,
   1.148
  ],
  "anims": [],
  "nodes": [
   "cloud_big"
  ]
 },
 "cloud-small": {
  "id": "cloud-small",
  "url": "/models/cloud-small.glb",
  "kb": 17,
  "tris": 366,
  "size": [
   2.338,
   1.84,
   1.792
  ],
  "min": [
   -1.163,
   -0.908,
   -0.963
  ],
  "max": [
   1.175,
   0.932,
   0.829
  ],
  "anims": [],
  "nodes": [
   "cloud_small"
  ]
 },
 "tent": {
  "id": "tent",
  "url": "/models/tent.glb",
  "kb": 16,
  "tris": 86,
  "size": [
   0.516,
   0.516,
   0.516
  ],
  "min": [
   -0.258,
   0,
   -0.258
  ],
  "max": [
   0.258,
   0.516,
   0.258
  ],
  "anims": [],
  "nodes": [
   "tent"
  ]
 },
 "flag-red": {
  "id": "flag-red",
  "url": "/models/flag-red.glb",
  "kb": 12,
  "tris": 48,
  "size": [
   0.055,
   0.277,
   0.264
  ],
  "min": [
   -0.027,
   0,
   -0.242
  ],
  "max": [
   0.028,
   0.277,
   0.022
  ],
  "anims": [],
  "nodes": [
   "flag_red"
  ]
 },
 "bridge-a": {
  "id": "bridge-a",
  "url": "/models/bridge-a.glb",
  "kb": 35,
  "tris": 604,
  "size": [
   1.333,
   1.25,
   1.924
  ],
  "min": [
   -0.667,
   -1,
   -0.962
  ],
  "max": [
   0.667,
   0.25,
   0.962
  ],
  "anims": [],
  "nodes": [
   "building_bridge_A"
  ]
 },
 "waterplant": {
  "id": "waterplant",
  "url": "/models/waterplant.glb",
  "kb": 12,
  "tris": 66,
  "size": [
   0.198,
   0.132,
   0.216
  ],
  "min": [
   -0.122,
   -0.02,
   -0.123
  ],
  "max": [
   0.076,
   0.113,
   0.093
  ],
  "anims": [],
  "nodes": [
   "waterplant_A"
  ]
 },
 "city-a": {
  "id": "city-a",
  "url": "/models/city-a.glb",
  "kb": 39,
  "tris": 435,
  "size": [
   1.207,
   1.55,
   1.45
  ],
  "min": [
   -0.603,
   0.1,
   -0.65
  ],
  "max": [
   0.603,
   1.65,
   0.8
  ],
  "anims": [],
  "nodes": [
   "building_A_withoutBase"
  ]
 },
 "city-b": {
  "id": "city-b",
  "url": "/models/city-b.glb",
  "kb": 48,
  "tris": 586,
  "size": [
   1.607,
   1.55,
   1.3
  ],
  "min": [
   -0.803,
   0.1,
   -0.65
  ],
  "max": [
   0.803,
   1.65,
   0.65
  ],
  "anims": [],
  "nodes": [
   "building_B_withoutBase"
  ]
 },
 "city-c": {
  "id": "city-c",
  "url": "/models/city-c.glb",
  "kb": 53,
  "tris": 666,
  "size": [
   1.207,
   2.25,
   1.3
  ],
  "min": [
   -0.603,
   0.1,
   -0.65
  ],
  "max": [
   0.603,
   2.35,
   0.65
  ],
  "anims": [],
  "nodes": [
   "building_C_withoutBase"
  ]
 },
 "city-d": {
  "id": "city-d",
  "url": "/models/city-d.glb",
  "kb": 65,
  "tris": 848,
  "size": [
   1.607,
   2.25,
   1.3
  ],
  "min": [
   -0.803,
   0.1,
   -0.65
  ],
  "max": [
   0.803,
   2.35,
   0.65
  ],
  "anims": [],
  "nodes": [
   "building_D_withoutBase"
  ]
 },
 "city-e": {
  "id": "city-e",
  "url": "/models/city-e.glb",
  "kb": 71,
  "tris": 950,
  "size": [
   2.007,
   2.25,
   1.45
  ],
  "min": [
   -1.003,
   0.1,
   -0.65
  ],
  "max": [
   1.003,
   2.35,
   0.8
  ],
  "anims": [],
  "nodes": [
   "building_E_withoutBase"
  ]
 },
 "city-f": {
  "id": "city-f",
  "url": "/models/city-f.glb",
  "kb": 80,
  "tris": 1097,
  "size": [
   2.007,
   2.25,
   1.3
  ],
  "min": [
   -1.003,
   0.1,
   -0.65
  ],
  "max": [
   1.003,
   2.35,
   0.65
  ],
  "anims": [],
  "nodes": [
   "building_F_withoutBase"
  ]
 },
 "city-g": {
  "id": "city-g",
  "url": "/models/city-g.glb",
  "kb": 78,
  "tris": 1053,
  "size": [
   2.007,
   2.25,
   1.45
  ],
  "min": [
   -1.003,
   0.1,
   -0.65
  ],
  "max": [
   1.003,
   2.35,
   0.8
  ],
  "anims": [],
  "nodes": [
   "building_G_withoutBase"
  ]
 },
 "city-h": {
  "id": "city-h",
  "url": "/models/city-h.glb",
  "kb": 95,
  "tris": 1333,
  "size": [
   2.007,
   2.95,
   1.3
  ],
  "min": [
   -1.003,
   0.1,
   -0.65
  ],
  "max": [
   1.003,
   3.05,
   0.65
  ],
  "anims": [],
  "nodes": [
   "building_H_withoutBase"
  ]
 },
 "watertower": {
  "id": "watertower",
  "url": "/models/watertower.glb",
  "kb": 19,
  "tris": 146,
  "size": [
   0.499,
   0.67,
   0.499
  ],
  "min": [
   -0.249,
   0,
   -0.249
  ],
  "max": [
   0.249,
   0.67,
   0.249
  ],
  "anims": [],
  "nodes": [
   "watertower"
  ]
 },
 "streetlight": {
  "id": "streetlight",
  "url": "/models/streetlight.glb",
  "kb": 17,
  "tris": 176,
  "size": [
   0.269,
   0.96,
   0.069
  ],
  "min": [
   -0.239,
   0,
   -0.035
  ],
  "max": [
   0.03,
   0.96,
   0.035
  ],
  "anims": [],
  "nodes": [
   "streetlight"
  ]
 },
 "car-taxi": {
  "id": "car-taxi",
  "url": "/models/car-taxi.glb",
  "kb": 67,
  "tris": 1112,
  "size": [
   0.419,
   0.434,
   0.938
  ],
  "min": [
   -0.209,
   -0.061,
   -0.472
  ],
  "max": [
   0.209,
   0.373,
   0.466
  ],
  "anims": [],
  "nodes": [
   "car_taxi_wheel_front_left",
   "car_taxi_wheel_front_right",
   "car_taxi_wheel_rear_left",
   "car_taxi_wheel_rear_right",
   "car_taxi"
  ]
 },
 "car-sedan": {
  "id": "car-sedan",
  "url": "/models/car-sedan.glb",
  "kb": 63,
  "tris": 1078,
  "size": [
   0.419,
   0.369,
   0.938
  ],
  "min": [
   -0.209,
   -0.061,
   -0.472
  ],
  "max": [
   0.209,
   0.308,
   0.466
  ],
  "anims": [],
  "nodes": [
   "car_sedan_wheel_front_left",
   "car_sedan_wheel_front_right",
   "car_sedan_wheel_rear_left",
   "car_sedan_wheel_rear_right",
   "car_sedan"
  ]
 },
 "bush": {
  "id": "bush",
  "url": "/models/bush.glb",
  "kb": 13,
  "tris": 72,
  "size": [
   0.189,
   0.381,
   0.199
  ],
  "min": [
   -0.089,
   0,
   -0.1
  ],
  "max": [
   0.1,
   0.381,
   0.1
  ],
  "anims": [],
  "nodes": [
   "bush"
  ]
 },
 "lander-a": {
  "id": "lander-a",
  "url": "/models/lander-a.glb",
  "kb": 91,
  "tris": 1464,
  "size": [
   1.372,
   1.192,
   1.422
  ],
  "min": [
   -0.672,
   0,
   -0.672
  ],
  "max": [
   0.7,
   1.192,
   0.75
  ],
  "anims": [],
  "nodes": [
   "lander_A"
  ]
 },
 "lander-b": {
  "id": "lander-b",
  "url": "/models/lander-b.glb",
  "kb": 82,
  "tris": 1208,
  "size": [
   1.372,
   1.095,
   1.422
  ],
  "min": [
   -0.672,
   0,
   -0.672
  ],
  "max": [
   0.7,
   1.095,
   0.75
  ],
  "anims": [],
  "nodes": [
   "lander_B"
  ]
 },
 "solarpanel": {
  "id": "solarpanel",
  "url": "/models/solarpanel.glb",
  "kb": 18,
  "tris": 118,
  "size": [
   0.9,
   0.371,
   0.45
  ],
  "min": [
   -0.45,
   0,
   -0.225
  ],
  "max": [
   0.45,
   0.371,
   0.225
  ],
  "anims": [],
  "nodes": [
   "solarpanel"
  ]
 },
 "windturbine-tall": {
  "id": "windturbine-tall",
  "url": "/models/windturbine-tall.glb",
  "kb": 42,
  "tris": 632,
  "size": [
   1.665,
   3,
   1
  ],
  "min": [
   -0.833,
   0,
   -0.555
  ],
  "max": [
   0.833,
   3,
   0.445
  ],
  "anims": [],
  "nodes": [
   "windturbine_tall_fan",
   "windturbine_tall"
  ]
 },
 "windturbine-low": {
  "id": "windturbine-low",
  "url": "/models/windturbine-low.glb",
  "kb": 56,
  "tris": 826,
  "size": [
   1.144,
   1.465,
   1.29
  ],
  "min": [
   -0.572,
   0,
   -0.645
  ],
  "max": [
   0.572,
   1.465,
   0.645
  ],
  "anims": [],
  "nodes": [
   "windturbine_low_fan",
   "windturbine_low"
  ]
 },
 "basemodule-a": {
  "id": "basemodule-a",
  "url": "/models/basemodule-a.glb",
  "kb": 48,
  "tris": 586,
  "size": [
   2.248,
   1,
   2.176
  ],
  "min": [
   -1.176,
   0,
   -1
  ],
  "max": [
   1.072,
   1,
   1.176
  ],
  "anims": [],
  "nodes": [
   "basemodule_A"
  ]
 },
 "basemodule-c": {
  "id": "basemodule-c",
  "url": "/models/basemodule-c.glb",
  "kb": 52,
  "tris": 644,
  "size": [
   2,
   1,
   2.206
  ],
  "min": [
   -1,
   0,
   -1
  ],
  "max": [
   1,
   1,
   1.206
  ],
  "anims": [],
  "nodes": [
   "basemodule_C"
  ]
 },
 "structure-tall": {
  "id": "structure-tall",
  "url": "/models/structure-tall.glb",
  "kb": 52,
  "tris": 670,
  "size": [
   1.75,
   2,
   1.75
  ],
  "min": [
   -0.875,
   0,
   -0.875
  ],
  "max": [
   0.875,
   2,
   0.875
  ],
  "anims": [],
  "nodes": [
   "structure_tall"
  ]
 },
 "space-rock-a": {
  "id": "space-rock-a",
  "url": "/models/space-rock-a.glb",
  "kb": 14,
  "tris": 30,
  "size": [
   0.533,
   0.25,
   0.5
  ],
  "min": [
   -0.217,
   0,
   -0.25
  ],
  "max": [
   0.317,
   0.25,
   0.25
  ],
  "anims": [],
  "nodes": [
   "rock_A"
  ]
 },
 "space-rocks-a": {
  "id": "space-rocks-a",
  "url": "/models/space-rocks-a.glb",
  "kb": 17,
  "tris": 88,
  "size": [
   1.314,
   0.354,
   1.643
  ],
  "min": [
   -0.79,
   0,
   -0.822
  ],
  "max": [
   0.524,
   0.354,
   0.821
  ],
  "anims": [],
  "nodes": [
   "rocks_A"
  ]
 },
 "drill": {
  "id": "drill",
  "url": "/models/drill.glb",
  "kb": 79,
  "tris": 1198,
  "size": [
   1.75,
   2,
   1.75
  ],
  "min": [
   -0.875,
   0,
   -0.875
  ],
  "max": [
   0.875,
   2,
   0.875
  ],
  "anims": [],
  "nodes": [
   "drill_module",
   "drill_structure"
  ]
 },
 "tree-dead-l": {
  "id": "tree-dead-l",
  "url": "/models/tree-dead-l.glb",
  "kb": 17,
  "tris": 256,
  "size": [
   2.302,
   5.066,
   1.377
  ],
  "min": [
   -1.322,
   -0.272,
   -0.726
  ],
  "max": [
   0.98,
   4.794,
   0.651
  ],
  "anims": [],
  "nodes": [
   "tree_dead_large"
  ]
 },
 "tree-dead-m": {
  "id": "tree-dead-m",
  "url": "/models/tree-dead-m.glb",
  "kb": 15,
  "tris": 216,
  "size": [
   1.809,
   4.189,
   0.467
  ],
  "min": [
   -0.485,
   -0.3,
   -0.233
  ],
  "max": [
   1.323,
   3.889,
   0.233
  ],
  "anims": [],
  "nodes": [
   "tree_dead_medium"
  ]
 },
 "pine-orange-l": {
  "id": "pine-orange-l",
  "url": "/models/pine-orange-l.glb",
  "kb": 27,
  "tris": 318,
  "size": [
   4.759,
   7.475,
   4.155
  ],
  "min": [
   -2.363,
   -0.555,
   -2.076
  ],
  "max": [
   2.397,
   6.92,
   2.079
  ],
  "anims": [],
  "nodes": [
   "tree_pine_orange_large"
  ]
 },
 "pine-orange-m": {
  "id": "pine-orange-m",
  "url": "/models/pine-orange-m.glb",
  "kb": 27,
  "tris": 318,
  "size": [
   3.33,
   5.872,
   3.12
  ],
  "min": [
   -1.677,
   -0.48,
   -1.355
  ],
  "max": [
   1.653,
   5.392,
   1.766
  ],
  "anims": [],
  "nodes": [
   "tree_pine_orange_medium"
  ]
 },
 "pine-yellow-l": {
  "id": "pine-yellow-l",
  "url": "/models/pine-yellow-l.glb",
  "kb": 27,
  "tris": 318,
  "size": [
   4.759,
   7.475,
   4.155
  ],
  "min": [
   -2.363,
   -0.555,
   -2.076
  ],
  "max": [
   2.397,
   6.92,
   2.079
  ],
  "anims": [],
  "nodes": [
   "tree_pine_yellow_large"
  ]
 },
 "lantern": {
  "id": "lantern",
  "url": "/models/lantern.glb",
  "kb": 22,
  "tris": 264,
  "size": [
   0.64,
   0.925,
   0.64
  ],
  "min": [
   -0.32,
   0,
   -0.32
  ],
  "max": [
   0.32,
   0.925,
   0.32
  ],
  "anims": [],
  "nodes": [
   "lantern_standing"
  ]
 },
 "arch": {
  "id": "arch",
  "url": "/models/arch.glb",
  "kb": 38,
  "tris": 436,
  "size": [
   4.218,
   4.414,
   0.77
  ],
  "min": [
   -2.109,
   0,
   -0.385
  ],
  "max": [
   2.109,
   4.414,
   0.385
  ],
  "anims": [],
  "nodes": [
   "arch"
  ]
 },
 "crypt": {
  "id": "crypt",
  "url": "/models/crypt.glb",
  "kb": 67,
  "tris": 952,
  "size": [
   6,
   8,
   8
  ],
  "min": [
   -3,
   0,
   -4
  ],
  "max": [
   3,
   8,
   4
  ],
  "anims": [],
  "nodes": [
   "crypt"
  ]
 },
 "pillar": {
  "id": "pillar",
  "url": "/models/pillar.glb",
  "kb": 16,
  "tris": 94,
  "size": [
   1,
   4.4,
   1
  ],
  "min": [
   -0.5,
   0,
   -0.5
  ],
  "max": [
   0.5,
   4.4,
   0.5
  ],
  "anims": [],
  "nodes": [
   "pillar"
  ]
 },
 "shrine": {
  "id": "shrine",
  "url": "/models/shrine.glb",
  "kb": 16,
  "tris": 94,
  "size": [
   1.099,
   2.4,
   1.099
  ],
  "min": [
   -0.55,
   0,
   -0.55
  ],
  "max": [
   0.55,
   2.4,
   0.55
  ],
  "anims": [],
  "nodes": [
   "shrine"
  ]
 },
 "boat-small": {
  "id": "boat-small",
  "url": "/models/boat-small.glb",
  "kb": 5,
  "tris": 104,
  "size": [
   0.892,
   0.35,
   1.483
  ],
  "min": [
   -0.771,
   0,
   -10.715
  ],
  "max": [
   0.121,
   0.35,
   -9.232
  ],
  "anims": [],
  "nodes": [
   "boat_small_8angles"
  ]
 },
 "boat-large": {
  "id": "boat-large",
  "url": "/models/boat-large.glb",
  "kb": 6,
  "tris": 126,
  "size": [
   0.893,
   0.35,
   1.773
  ],
  "min": [
   0.864,
   0,
   -10.715
  ],
  "max": [
   1.757,
   0.35,
   -8.942
  ],
  "anims": [],
  "nodes": [
   "boat_large_8angles"
  ]
 },
 "ship-light": {
  "id": "ship-light",
  "url": "/models/ship-light.glb",
  "kb": 289,
  "tris": 6302,
  "size": [
   2.851,
   6.547,
   8.098
  ],
  "min": [
   -2.14,
   0,
   -4.835
  ],
  "max": [
   0.711,
   6.547,
   3.262
  ],
  "anims": [],
  "nodes": [
   "cannon_front 1.001",
   "cannon_front 1",
   "cannon_left 1.001",
   "cannon_left 1.002",
   "cannon_left 1.003",
   "cannon_left 1.004",
   "cannon_left 1.005",
   "cannon_left 1",
   "cannon_right 1.001",
   "cannon_right 1.002",
   "cannon_right 1.003",
   "cannon_right 1.004",
   "cannon_right 1.005",
   "cannon_right 1",
   "sail_back 1",
   "sail_front 1",
   "sail_middle 1",
   "steering 1",
   "ship_light_8angles"
  ]
 },
 "ship-dark": {
  "id": "ship-dark",
  "url": "/models/ship-dark.glb",
  "kb": 288,
  "tris": 6302,
  "size": [
   2.851,
   6.547,
   8.098
  ],
  "min": [
   2.845,
   0,
   -4.835
  ],
  "max": [
   5.696,
   6.547,
   3.262
  ],
  "anims": [],
  "nodes": [
   "cannon_front.001",
   "cannon_front",
   "cannon_left.001",
   "cannon_left.002",
   "cannon_left.003",
   "cannon_left.004",
   "cannon_left.005",
   "cannon_left",
   "cannon_right.001",
   "cannon_right.002",
   "cannon_right.003",
   "cannon_right.004",
   "cannon_right.005",
   "cannon_right",
   "sail_back",
   "sail_front",
   "sail_middle",
   "steering",
   "ship_dark_8angles"
  ]
 },
 "pirate-tower": {
  "id": "pirate-tower",
  "url": "/models/pirate-tower.glb",
  "kb": 46,
  "tris": 1004,
  "size": [
   3.323,
   3.715,
   3.34
  ],
  "min": [
   -7.547,
   0,
   -3.217
  ],
  "max": [
   -4.224,
   3.715,
   0.124
  ],
  "anims": [],
  "nodes": [
   "tower"
  ]
 },
 "rock-formation": {
  "id": "rock-formation",
  "url": "/models/rock-formation.glb",
  "kb": 9,
  "tris": 172,
  "size": [
   1.06,
   1.225,
   1.067
  ],
  "min": [
   4.635,
   0,
   -10.669
  ],
  "max": [
   5.695,
   1.225,
   -9.601
  ],
  "anims": [],
  "nodes": [
   "formation_rock"
  ]
 },
 "stone-formation": {
  "id": "stone-formation",
  "url": "/models/stone-formation.glb",
  "kb": 8,
  "tris": 172,
  "size": [
   1.06,
   1.225,
   1.067
  ],
  "min": [
   4.635,
   0,
   -9.009
  ],
  "max": [
   5.695,
   1.225,
   -7.942
  ],
  "anims": [],
  "nodes": [
   "formation_stone"
  ]
 },
 "rock-formation-l": {
  "id": "rock-formation-l",
  "url": "/models/rock-formation-l.glb",
  "kb": 8,
  "tris": 136,
  "size": [
   1.362,
   1.38,
   0.947
  ],
  "min": [
   2.683,
   0,
   -10.639
  ],
  "max": [
   4.045,
   1.38,
   -9.692
  ],
  "anims": [],
  "nodes": [
   "formationLarge_rock"
  ]
 },
 "stone-formation-l": {
  "id": "stone-formation-l",
  "url": "/models/stone-formation-l.glb",
  "kb": 7,
  "tris": 136,
  "size": [
   1.362,
   1.38,
   0.947
  ],
  "min": [
   2.683,
   0,
   -8.978
  ],
  "max": [
   4.045,
   1.38,
   -8.032
  ],
  "anims": [],
  "nodes": [
   "formationLarge_stone"
  ]
 },
 "palm-long": {
  "id": "palm-long",
  "url": "/models/palm-long.glb",
  "kb": 12,
  "tris": 194,
  "size": [
   1.544,
   2.023,
   1.544
  ],
  "min": [
   4.814,
   0,
   -7.168
  ],
  "max": [
   6.358,
   2.023,
   -5.624
  ],
  "anims": [],
  "nodes": [
   "Group 28",
   "Group 30"
  ]
 },
 "palm-short": {
  "id": "palm-short",
  "url": "/models/palm-short.glb",
  "kb": 12,
  "tris": 194,
  "size": [
   1.544,
   1.576,
   1.544
  ],
  "min": [
   3.597,
   0,
   -7.168
  ],
  "max": [
   5.141,
   1.576,
   -5.624
  ],
  "anims": [],
  "nodes": [
   "Group 23",
   "Group 25"
  ]
 },
 "palm-detailed-long": {
  "id": "palm-detailed-long",
  "url": "/models/palm-detailed-long.glb",
  "kb": 23,
  "tris": 488,
  "size": [
   1.544,
   2.125,
   1.544
  ],
  "min": [
   2.379,
   0,
   -7.168
  ],
  "max": [
   3.923,
   2.125,
   -5.624
  ],
  "anims": [],
  "nodes": [
   "Group 152",
   "Group 154"
  ]
 },
 "palm-detailed-short": {
  "id": "palm-detailed-short",
  "url": "/models/palm-detailed-short.glb",
  "kb": 23,
  "tris": 488,
  "size": [
   1.544,
   1.678,
   1.544
  ],
  "min": [
   1.162,
   0,
   -7.168
  ],
  "max": [
   2.706,
   1.678,
   -5.624
  ],
  "anims": [],
  "nodes": [
   "Group 18",
   "Group 20"
  ]
 },
 "tree-big": {
  "id": "tree-big",
  "url": "/models/tree-big.glb",
  "kb": 18,
  "tris": 556,
  "size": [
   0.211,
   0.767,
   0.236
  ],
  "min": [
   -0.105,
   0,
   -0.118
  ],
  "max": [
   0.105,
   0.767,
   0.118
  ],
  "anims": [],
  "nodes": [
   "tree_large"
  ]
 },
 "tree-small": {
  "id": "tree-small",
  "url": "/models/tree-small.glb",
  "kb": 18,
  "tris": 556,
  "size": [
   0.26,
   0.7,
   0.298
  ],
  "min": [
   -0.13,
   0,
   -0.149
  ],
  "max": [
   0.13,
   0.7,
   0.149
  ],
  "anims": [],
  "nodes": [
   "tree_small"
  ]
 },
 "tree-round": {
  "id": "tree-round",
  "url": "/models/tree-round.glb",
  "kb": 113,
  "tris": 4540,
  "size": [
   1.703,
   2.295,
   1.511
  ],
  "min": [
   -0.739,
   -0.49,
   -0.795
  ],
  "max": [
   0.964,
   1.805,
   0.717
  ],
  "anims": [],
  "nodes": [
   "Cube",
   "Cube.002",
   "Cube.003",
   "Cube.004",
   "Cube.005",
   "Cube.006",
   "Cube.007",
   "Cube.008",
   "Cube.009",
   "Cube.010",
   "Cube.011",
   "Cube.012",
   "Cube.025",
   "Tree"
  ]
 },
 "house-3": {
  "id": "house-3",
  "url": "/models/house-3.glb",
  "kb": 28,
  "tris": 580,
  "size": [
   1.708,
   1.138,
   0.916
  ],
  "min": [
   -0.854,
   0,
   -0.458
  ],
  "max": [
   0.854,
   1.138,
   0.458
  ],
  "anims": [],
  "nodes": [
   "house_type03"
  ]
 },
 "house-5": {
  "id": "house-5",
  "url": "/models/house-5.glb",
  "kb": 34,
  "tris": 688,
  "size": [
   1.736,
   1.2,
   1.006
  ],
  "min": [
   -0.868,
   0,
   -0.503
  ],
  "max": [
   0.868,
   1.2,
   0.503
  ],
  "anims": [],
  "nodes": [
   "house_type08"
  ]
 },
 "house-7": {
  "id": "house-7",
  "url": "/models/house-7.glb",
  "kb": 20,
  "tris": 398,
  "size": [
   1.2,
   0.85,
   0.81
  ],
  "min": [
   -0.6,
   0,
   -0.405
  ],
  "max": [
   0.6,
   0.85,
   0.405
  ],
  "anims": [],
  "nodes": [
   "house_type19"
  ]
 },
 "library": {
  "id": "library",
  "url": "/models/library.glb",
  "kb": 82,
  "tris": 1150,
  "size": [
   2.624,
   1.641,
   3.593
  ],
  "min": [
   -1.265,
   -0.252,
   -2.301
  ],
  "max": [
   1.359,
   1.39,
   1.292
  ],
  "anims": [],
  "nodes": [
   "Library_large"
  ]
 },
 "ferris-wheel": {
  "id": "ferris-wheel",
  "url": "/models/ferris-wheel.glb",
  "kb": 277,
  "tris": 4914,
  "size": [
   1.917,
   2.284,
   0.5
  ],
  "min": [
   -0.957,
   -1.238,
   -0.252
  ],
  "max": [
   0.96,
   1.046,
   0.247
  ],
  "anims": [],
  "nodes": [
   "Ferris_Wheel"
  ]
 },
 "wind-turbine": {
  "id": "wind-turbine",
  "url": "/models/wind-turbine.glb",
  "kb": 99,
  "tris": 2586,
  "size": [
   4.215,
   6.81,
   1.333
  ],
  "min": [
   -2.501,
   -0.003,
   -0.6
  ],
  "max": [
   1.713,
   6.807,
   0.733
  ],
  "anims": [
   "Wind_turbine_001_BladesAction"
  ],
  "nodes": [
   "Wind_turbine_001_Blades",
   "Wind_turbine_001"
  ]
 },
 "bridge-stone": {
  "id": "bridge-stone",
  "url": "/models/bridge-stone.glb",
  "kb": 79,
  "tris": 3198,
  "size": [
   4.494,
   0.755,
   2.16
  ],
  "min": [
   -2.201,
   -0.197,
   -1.073
  ],
  "max": [
   2.292,
   0.558,
   1.087
  ],
  "anims": [],
  "nodes": [
   "Bridge.01"
  ]
 },
 "chest": {
  "id": "chest",
  "url": "/models/chest.glb",
  "kb": 22,
  "tris": 452,
  "size": [
   0.49,
   0.549,
   0.438
  ],
  "min": [
   -2.875,
   0,
   -6.513
  ],
  "max": [
   -2.385,
   0.549,
   -6.075
  ],
  "anims": [],
  "nodes": [
   "lid",
   "chest"
  ]
 },
 "present": {
  "id": "present",
  "url": "/models/present.glb",
  "kb": 1286,
  "tris": 69248,
  "size": [
   1.582,
   1.861,
   1.868
  ],
  "min": [
   -0.782,
   -0.628,
   -0.896
  ],
  "max": [
   0.8,
   1.233,
   0.971
  ],
  "anims": [],
  "nodes": [
   "BezierCircle",
   "Cube.001",
   "Cube.002",
   "NurbsPath",
   "Cube"
  ]
 },
 "crate": {
  "id": "crate",
  "url": "/models/crate.glb",
  "kb": 159,
  "tris": 6092,
  "size": [
   1.299,
   1.552,
   1.329
  ],
  "min": [
   -0.649,
   0,
   -0.649
  ],
  "max": [
   0.649,
   1.552,
   0.68
  ],
  "anims": [],
  "nodes": [
   "crate.003"
  ]
 },
 "cactus": {
  "id": "cactus",
  "url": "/models/cactus.glb",
  "kb": 394,
  "tris": 10713,
  "size": [
   1.576,
   1.883,
   1.576
  ],
  "min": [
   -0.694,
   0.037,
   -0.663
  ],
  "max": [
   0.882,
   1.919,
   0.913
  ],
  "anims": [],
  "nodes": [
   "pot",
   "ground",
   "cactus",
   "Cylinder.004",
   "Cylinder.005",
   "Cylinder.007",
   "Cylinder.009",
   "Cylinder.011",
   "Cylinder.013",
   "Cylinder.015",
   "Cylinder.017"
  ]
 },
 "barn": {
  "id": "barn",
  "url": "/models/barn.glb",
  "kb": 1042,
  "tris": 19274,
  "size": [
   3.204,
   2.822,
   4.495
  ],
  "min": [
   -1.598,
   0,
   -2.098
  ],
  "max": [
   1.606,
   2.822,
   2.397
  ],
  "anims": [],
  "nodes": [
   "Barn_001"
  ]
 }
} as const satisfies Record<string, ModelInfo>
export type ModelId = keyof typeof MODELS
export const MATERIALS = {
 "grass": {
  "color": "/textures/grass-color.webp",
  "normal": "/textures/grass-normal.webp",
  "rough": "/textures/grass-rough.webp"
 },
 "rock": {
  "color": "/textures/rock-color.webp",
  "normal": "/textures/rock-normal.webp",
  "rough": "/textures/rock-rough.webp"
 }
} as const
export const TEXTURES = {
 "waternormals": "/textures/waternormals.jpg",
 "lensflare0": "/textures/lensflare0.png",
 "lensflare3": "/textures/lensflare3.png",
 "cloud-noise": "/textures/cloud-noise.webp",
 "lavatile": "/textures/lavatile.webp",
 "sprite-spark": "/textures/sprite-spark.png",
 "sprite-disc": "/textures/sprite-disc.png",
 "sprite-circle": "/textures/sprite-circle.png",
 "sprite-snow": "/textures/sprite-snow.png"
} as const
export const HDRIS = {
 "venice-sunset": "/hdr/venice-sunset.hdr",
 "moonless-golf": "/hdr/moonless-golf.hdr"
} as const
export const FONTS = [
 {
  "family": "Bungee",
  "weight": 400,
  "file": "bungee-400.woff2"
 },
 {
  "family": "Rubik",
  "weight": 400,
  "file": "rubik-400.woff2"
 },
 {
  "family": "Rubik",
  "weight": 500,
  "file": "rubik-500.woff2"
 },
 {
  "family": "Rubik",
  "weight": 700,
  "file": "rubik-700.woff2"
 }
] as const
